import { Product, ProductReview } from './types';

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    slug: 'chronos-pulse-cyber',
    name: 'Chronos Pulse Cyber-Digital',
    subtitle: 'Urban Stealth & Precision Pulse',
    brand: 'Chronos Lab',
    price: 185,
    originalPrice: 220,
    rating: 4.8,
    reviewCount: 34,
    images: [
      'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1511370235399-1802cae1d32f?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Digital',
    ageGroup: '15-24',
    movement: 'Hybrid Cyber',
    strapMaterial: 'Tactical Silicone',
    inStock: true,
    stockQuantity: 28,
    featured: true,
    isNewArrival: true,
    isBestSeller: false,
    description: 'Designed for the next generation of urban explorers, the Chronos Pulse blends aggressive tactical aesthetics with modern hybrid timekeeping and customizable ambient backlighting.',
    longDescription: 'Crafted with a lightweight shock-absorbing composite chassis and an ultra-durable tactical silicone strap, the Chronos Pulse is built to endure dynamic daily wear. Featuring dual-time zone displays, precision stopwatch functions, and an eye-catching LED backlit dial, this timepiece bridges streetwear culture with high-function horology.',
    highlights: [
      'High-contrast tactical LED digital/analog hybrid dial',
      'Impact-resistant polycarbonate casing with matte finish',
      'Flexible breathable silicone band with double-pin clasp',
      'Water resistant to 50 meters (5 ATM)',
      'Subtle ambient blue backlight mode for nocturnal visibility'
    ],
    specs: {
      caseDiameter: '42 mm',
      caseThickness: '11.5 mm',
      caseMaterial: 'Carbon Composite & Stainless Back',
      waterResistance: '50 Meters / 5 ATM',
      movement: 'Hybrid Cyber',
      glass: 'Hardened Mineral Crystal',
      strapWidth: '22 mm',
      dialColor: 'Midnight Tactical Black',
      warranty: '2 Year International Warranty',
      powerReserve: '3 Year Battery Life'
    },
    variants: [
      { id: 'v1', colorName: 'Tactical Black', hex: '#111216', image: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1000&q=80' },
      { id: 'v2', colorName: 'Cyber Orange', hex: '#FF6B00', image: 'https://images.unsplash.com/photo-1511370235399-1802cae1d32f?auto=format&fit=crop&w=1000&q=80' }
    ]
  },
  {
    id: 'prod-02',
    slug: 'aura-minimalist-neo-chrono',
    name: 'Aura Minimalist Neo-Chrono',
    subtitle: 'Nordic Simplicity Meets Precision',
    brand: 'Aura Horology',
    price: 245,
    originalPrice: 280,
    rating: 4.9,
    reviewCount: 52,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Minimalist',
    ageGroup: '15-24',
    movement: 'Quartz',
    strapMaterial: 'Milanese Mesh',
    inStock: true,
    stockQuantity: 45,
    featured: true,
    isNewArrival: false,
    isBestSeller: true,
    description: 'An architectural study in simplicity. Clean eggshell dial with flame-blued hands and quick-change Milanese steel strap.',
    longDescription: 'The Aura Neo-Chrono redefines minimalist luxury for students and young creatives. Stripping away unnecessary clutter, it features crisp applied indices, sub-second chronograph registers, and an ultra-thin 7.5mm profile that slips effortlessly under shirt cuffs.',
    highlights: [
      'Ultra-slim 7.5mm profile stainless steel case',
      'Quick-release interchangeable Milanese mesh bracelet',
      'Precision Japanese Miyota chronograph quartz movement',
      'Scratch-resistant sapphire-coated glass'
    ],
    specs: {
      caseDiameter: '40 mm',
      caseThickness: '7.5 mm',
      caseMaterial: '316L Surgical Grade Stainless Steel',
      waterResistance: '30 Meters / 3 ATM',
      movement: 'Quartz',
      glass: 'Sapphire Crystal Coated',
      strapWidth: '20 mm',
      dialColor: 'Eggshell White & Blue Steel Hands',
      warranty: '3 Year Manufacturer Warranty',
      powerReserve: '2 Year Battery Life'
    }
  },
  {
    id: 'prod-03',
    slug: 'vance-co-urban-speed',
    name: 'Vance & Co. Urban Speed',
    subtitle: 'Motorsport Spirit For The Modern Driver',
    brand: 'Vance & Co.',
    price: 320,
    originalPrice: 380,
    rating: 4.7,
    reviewCount: 29,
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1547996160-01ff70028a7c?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Chronograph',
    ageGroup: '15-24',
    movement: 'Quartz',
    strapMaterial: 'Italian Leather',
    inStock: true,
    stockQuantity: 19,
    featured: false,
    isNewArrival: true,
    isBestSeller: false,
    description: 'Tachymeter bezel, racing sub-dials, and perforated rally leather band inspired by classic endurance racing.',
    longDescription: 'Engineered for speed enthusiasts and dynamic lifestyles, the Vance & Co. Urban Speed features high-contrast timing registers, high-precision split-second measurement, and supple handcrafted Italian rally leather that develops a rich patina over time.',
    highlights: [
      'Engraved tachymeter scale bezel for speed calculations',
      'Perforated rally leather strap with custom buckle',
      'Chronograph accuracy to 1/10th of a second',
      'Luminous hands and hour markers'
    ],
    specs: {
      caseDiameter: '41.5 mm',
      caseThickness: '10.8 mm',
      caseMaterial: 'Brushed Stainless Steel',
      waterResistance: '100 Meters / 10 ATM',
      movement: 'Quartz',
      glass: 'Hardened Mineral Glass',
      strapWidth: '20 mm',
      dialColor: 'Carbon Matte Black',
      warranty: '2 Year Warranty',
      powerReserve: '3 Year Battery Life'
    }
  },
  {
    id: 'prod-04',
    slug: 'grand-sovereign-skeleton-auto',
    name: 'Grand Sovereign Skeleton Automatic',
    subtitle: 'Exposed Mechanical Mastery & Pure Elegance',
    brand: 'Sovereign Geneva',
    price: 1290,
    originalPrice: 1550,
    rating: 5.0,
    reviewCount: 68,
    images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Skeleton',
    ageGroup: '25-38',
    movement: 'Automatic Mechanical',
    strapMaterial: 'Italian Leather',
    inStock: true,
    stockQuantity: 12,
    featured: true,
    isNewArrival: true,
    isBestSeller: true,
    description: 'Full skeletonized mechanical movement framed in rose gold, showcasing the beating heart of Swiss horology.',
    longDescription: 'The pinnacle of open-heart craftsmanship. The Grand Sovereign Skeleton reveals every gear, jewel, and balance wheel in motion. Powered by the motion of your wrist, this self-winding masterpiece requires no batteries and boasts a 42-hour power reserve with double anti-reflective sapphire crystal on both front and exhibition back.',
    highlights: [
      'Hand-finished 21-jewel automatic movement with openwork movement',
      '18K Rose Gold PVD vacuum plated 316L case',
      'Exhibition exhibition caseback revealing decorated rotor',
      'Hand-stitched crocodile grain Italian leather strap',
      'Dual anti-reflective scratchproof sapphire crystal'
    ],
    specs: {
      caseDiameter: '42 mm',
      caseThickness: '11.8 mm',
      caseMaterial: '316L Stainless Steel with Rose Gold PVD',
      waterResistance: '50 Meters / 5 ATM',
      movement: 'Automatic Mechanical',
      glass: 'Sapphire Crystal AR Coated',
      strapWidth: '22 mm',
      dialColor: 'Rose Gold & Skeleton Mechanical',
      warranty: '5 Year Sovereign Warranty',
      powerReserve: '42 Hours'
    }
  },
  {
    id: 'prod-05',
    slug: 'apex-executive-chronograph',
    name: 'Apex Executive Chronograph',
    subtitle: 'Midnight Blue Sunray Dial & Steel Precision',
    brand: 'Aura Horology',
    price: 890,
    originalPrice: 1050,
    rating: 4.9,
    reviewCount: 41,
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Chronograph',
    ageGroup: '25-38',
    movement: 'Quartz',
    strapMaterial: '316L Stainless Steel',
    inStock: true,
    stockQuantity: 22,
    featured: true,
    isNewArrival: false,
    isBestSeller: true,
    description: 'Deep sunray blue dial with silver chronograph registers, integrated solid steel link bracelet, and butterfly clasp.',
    longDescription: 'Built for boardroom performance and evening sophistication, the Apex Executive commands respect. Its multi-layered dial catches light at every angle, while solid end-link construction ensures a weight and presence on the wrist that defines modern luxury.',
    highlights: [
      'Rich sunray midnight blue dial with applied baton markers',
      'Solid-link 316L stainless steel bracelet with push-button butterfly deployment clasp',
      'Date display window at 4 o clock position',
      'Swiss precision quartz chronograph caliber'
    ],
    specs: {
      caseDiameter: '41 mm',
      caseThickness: '10.5 mm',
      caseMaterial: 'Polished & Satin Brushed Stainless Steel',
      waterResistance: '100 Meters / 10 ATM',
      movement: 'Quartz',
      glass: 'Sapphire Crystal',
      strapWidth: '20 mm',
      dialColor: 'Midnight Sunray Blue',
      warranty: '3 Year International Warranty',
      powerReserve: '3 Year Battery Life'
    }
  },
  {
    id: 'prod-06',
    slug: 'aura-heritage-diver-300m',
    name: 'Aura Heritage Diver 300M',
    subtitle: 'Professional Deep Water Automatic Diver',
    brand: 'Aura Horology',
    price: 760,
    originalPrice: 890,
    rating: 4.8,
    reviewCount: 38,
    images: [
      'https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1547996160-01ff70028a7c?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Dive',
    ageGroup: '25-38',
    movement: 'Automatic Mechanical',
    strapMaterial: '316L Stainless Steel',
    inStock: true,
    stockQuantity: 15,
    featured: false,
    isNewArrival: true,
    isBestSeller: false,
    description: '120-click ceramic rotating bezel, Swiss Super-LumiNova markers, 300m water resistance, and helium escape valve.',
    longDescription: 'Whether exploring oceanic depths or navigating daily life, the Heritage Diver 300M offers uncompromised tool-watch performance. Features an scratch-proof ceramic bezel insert, screw-down crown with double O-ring gaskets, and high-visibility luminescent indices.',
    highlights: [
      '300 meters (1000 ft) water resistance rating',
      'Unidirectional ceramic bezel with engraved scale',
      'Grade A Swiss Super-LumiNova on hands and hour markers',
      'Reliable NH35 Japanese self-winding automatic movement'
    ],
    specs: {
      caseDiameter: '42.5 mm',
      caseThickness: '13.2 mm',
      caseMaterial: '316L Stainless Steel',
      waterResistance: '300 Meters / 30 ATM',
      movement: 'Automatic Mechanical',
      glass: 'Flat Sapphire with Inner Anti-Reflective Coating',
      strapWidth: '22 mm',
      dialColor: 'Deep Ocean Navy',
      warranty: '3 Year Diver Warranty',
      powerReserve: '41 Hours'
    }
  },
  {
    id: 'prod-07',
    slug: 'vance-co-horizon-gmt',
    name: 'Vance & Co. Horizon GMT',
    subtitle: 'Dual-Time Zone Traveler Chronometer',
    brand: 'Vance & Co.',
    price: 980,
    originalPrice: 1150,
    rating: 4.9,
    reviewCount: 27,
    images: [
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Dress',
    ageGroup: '25-38',
    movement: 'Automatic Mechanical',
    strapMaterial: 'Italian Leather',
    inStock: true,
    stockQuantity: 18,
    featured: false,
    isNewArrival: false,
    isBestSeller: true,
    description: 'Bi-color 24-hour bezel with independently adjustable GMT hand for seamless tracking of two time zones.',
    longDescription: 'Tailored for international executives, frequent fliers, and style connoisseurs. The Horizon GMT combines GMT complication utility with refined champagne dial accents and a quick-release leather strap.',
    highlights: [
      '4-hand GMT complication with caller time-zone adjustment',
      'Bi-directional 24-hour rotatable bezel',
      'Grained champagne dial with date magnification window',
      'Top-grain Italian calfskin strap with signed buckle'
    ],
    specs: {
      caseDiameter: '40 mm',
      caseThickness: '12 mm',
      caseMaterial: '316L Stainless Steel',
      waterResistance: '100 Meters / 10 ATM',
      movement: 'Automatic Mechanical',
      glass: 'Domed Sapphire Crystal',
      strapWidth: '20 mm',
      dialColor: 'Champagne & Midnight Blue',
      warranty: '3 Year International Warranty',
      powerReserve: '38 Hours'
    }
  },
  {
    id: 'prod-08',
    slug: 'royal-masterpiece-tourbillon',
    name: 'Royal Masterpiece Tourbillon',
    subtitle: 'Exquisite Haute Horlogerie Flying Tourbillon',
    brand: 'Sovereign Geneva',
    price: 4800,
    originalPrice: 5500,
    rating: 5.0,
    reviewCount: 19,
    images: [
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Luxury',
    ageGroup: '39-60',
    movement: 'Manual Wind',
    strapMaterial: 'Rose Gold Plated',
    inStock: true,
    stockQuantity: 4,
    featured: true,
    isNewArrival: true,
    isBestSeller: true,
    description: 'Flying Tourbillon cage rotation at 6 o clock, 18K Solid Rose Gold electroplated case, hand-engraved bridge plates, presentation wooden case.',
    longDescription: 'The pinnacle of fine watchmaking art. The Royal Masterpiece Flying Tourbillon defies gravitational pull on the balance wheel while showcasing intricate anglage, Côtes de Genève polishing, and blued steel screws. A true heirloom piece designed for generations.',
    highlights: [
      'Co-axial Flying Tourbillon mechanism rotating 360 degrees every 60 seconds',
      '18K Rose Gold electroplated casing with polished bevels',
      'Delivered in handcrafted piano-finished mahogany watch winder box',
      'Hand-stitched genuine alligator leather strap with folding gold deployment buckle',
      'Numbered limited edition release of 200 pieces worldwide'
    ],
    specs: {
      caseDiameter: '43 mm',
      caseThickness: '12.5 mm',
      caseMaterial: '316L Stainless Steel with 10 Micron 18K Rose Gold Gold-Plate',
      waterResistance: '50 Meters / 5 ATM',
      movement: 'Manual Wind',
      glass: 'Scratchproof Sapphire Crystal with Anti-Glare Coating',
      strapWidth: '22 mm',
      dialColor: 'Silver Guilloché & Open Tourbillon',
      warranty: 'Lifetime Sovereign Warranty',
      powerReserve: '60 Hours'
    }
  },
  {
    id: 'prod-09',
    slug: 'grand-sovereign-perpetual-calendar',
    name: 'Grand Sovereign Perpetual Calendar',
    subtitle: 'Moonphase & Grand Complication Heritage',
    brand: 'Sovereign Geneva',
    price: 2450,
    originalPrice: 2800,
    rating: 4.9,
    reviewCount: 44,
    images: [
      'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Luxury',
    ageGroup: '39-60',
    movement: 'Automatic Mechanical',
    strapMaterial: 'Italian Leather',
    inStock: true,
    stockQuantity: 8,
    featured: true,
    isNewArrival: false,
    isBestSeller: true,
    description: 'Enamel moonphase aperture, calendar sub-dials for day, date, and month, with classical Roman hour numerals.',
    longDescription: 'Embodying century-old horological traditions, the Grand Sovereign Perpetual Calendar automatically tracks month lengths and moon phases with poetic precision. Finished with flame-blued hands, a silver sunburst dial, and dark chestnut alligator-grain strap.',
    highlights: [
      'Photorealistic enamel moonphase disc display at 6 o clock',
      'Complete calendar complication tracking day of week, date, and month',
      'Flame-blued leaf hands and printed traditional Roman numerals',
      'Custom engraved automatic rotor visible through sapphire caseback'
    ],
    specs: {
      caseDiameter: '41 mm',
      caseThickness: '11.6 mm',
      caseMaterial: 'Polished 316L Stainless Steel',
      waterResistance: '50 Meters / 5 ATM',
      movement: 'Automatic Mechanical',
      glass: 'Double Curved Sapphire Glass',
      strapWidth: '20 mm',
      dialColor: 'Opaline Silver with Blue Hands',
      warranty: '5 Year Sovereign Warranty',
      powerReserve: '48 Hours'
    }
  },
  {
    id: 'prod-10',
    slug: 'aura-vintage-revival-1968',
    name: 'Aura Vintage Revival 1968',
    subtitle: 'Retro Cushion Case & Patina Warmth',
    brand: 'Aura Horology',
    price: 1150,
    originalPrice: 1350,
    rating: 4.8,
    reviewCount: 31,
    images: [
      'https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Dress',
    ageGroup: '39-60',
    movement: 'Manual Wind',
    strapMaterial: 'Italian Leather',
    inStock: true,
    stockQuantity: 14,
    featured: false,
    isNewArrival: false,
    isBestSeller: false,
    description: 'Cushion-shaped vintage case, domed box sapphire crystal, faux-patina radium lume, and tactile manual wind mechanism.',
    longDescription: 'A loving homage to mid-century chronograph designs. The Vintage Revival 1968 re-creates the nostalgic tactile pleasure of winding your timepiece every morning, housed in a meticulously brushed cushion case with vintage warm cream tones.',
    highlights: [
      'Vintage cushion-style 1960s casing design',
      'Box-shaped domed anti-scratch sapphire glass',
      'Old-radium shade Swiss Super-LumiNova luminescence',
      'Hand-wound mechanical movement with smooth tactile click feedback'
    ],
    specs: {
      caseDiameter: '39 mm',
      caseThickness: '11 mm',
      caseMaterial: 'Brushed & Polished Stainless Steel',
      waterResistance: '50 Meters / 5 ATM',
      movement: 'Manual Wind',
      glass: 'Domed Box Sapphire Glass',
      strapWidth: '20 mm',
      dialColor: 'Vintage Cream & Patina Lume',
      warranty: '3 Year Warranty',
      powerReserve: '45 Hours'
    }
  },
  {
    id: 'prod-11',
    slug: 'veloce-regent-diamond-edition',
    name: 'Veloce Regent Diamond Edition',
    subtitle: 'Fluted Gold Bezel & Diamond Index Markers',
    brand: 'Veloce Geneva',
    price: 1850,
    originalPrice: 2100,
    rating: 4.9,
    reviewCount: 23,
    images: [
      'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Luxury',
    ageGroup: '39-60',
    movement: 'Automatic Mechanical',
    strapMaterial: 'Rose Gold Plated',
    inStock: true,
    stockQuantity: 9,
    featured: true,
    isNewArrival: true,
    isBestSeller: false,
    description: 'Fluted bezel, champagne dial with 10 lab-grown diamond hour markers, and 5-link Jubilee bracelet.',
    longDescription: 'Expressing timeless sophistication, the Regent Diamond Edition combines the light-catching brilliance of a fluted bezel with genuine certified brilliant-cut lab diamond index markers and a supple Jubilee bracelet.',
    highlights: [
      '10 brilliant-cut VS1 clarity lab-grown diamond hour markers',
      'Precision fluted yellow-gold PVD bezel',
      'Cyclops date loupe at 3 o clock for 2.5x magnification',
      'Swiss COSC Certified automatic chronometer movement'
    ],
    specs: {
      caseDiameter: '40 mm',
      caseThickness: '11.5 mm',
      caseMaterial: '316L Stainless Steel & 18K Yellow Gold PVD',
      waterResistance: '100 Meters / 10 ATM',
      movement: 'Automatic Mechanical',
      glass: 'Sapphire Crystal with Cyclops Date Lens',
      strapWidth: '20 mm',
      dialColor: 'Champagne Gold with Diamond Markers',
      warranty: '5 Year Veloce Guarantee',
      powerReserve: '50 Hours'
    }
  },
  {
    id: 'prod-12',
    slug: 'aura-pure-slate-titanium',
    name: 'Aura Pure Slate Titanium',
    subtitle: 'Featherlight Grade 5 Titanium Minimalist',
    brand: 'Aura Horology',
    price: 340,
    originalPrice: 390,
    rating: 4.7,
    reviewCount: 35,
    images: [
      'https://images.unsplash.com/photo-1526045612212-70caf35c14df?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?auto=format&fit=crop&w=1000&q=80',
    ],
    category: 'Minimalist',
    ageGroup: 'all',
    movement: 'Solar Powered',
    strapMaterial: 'Titanium',
    inStock: true,
    stockQuantity: 30,
    featured: false,
    isNewArrival: false,
    isBestSeller: true,
    description: 'Grade 5 aerospace titanium case weighing under 45g with eco-solar power dial requiring zero battery changes.',
    longDescription: 'Crafted from hypoallergenic, ultra-durable Grade 5 Titanium, the Pure Slate Minimalist is imperceptible on the wrist. Invisible solar cells beneath the slate dial continuously charge from ambient light, keeping the watch powered indefinitely.',
    highlights: [
      'Ultra-lightweight Grade 5 Titanium case (42 grams total weight)',
      'Solar-powered dial converts indoor and outdoor light into power',
      '6-month power reserve on a single full charge in complete darkness',
      'Scratch-proof sapphire glass with anti-fingerprint coating'
    ],
    specs: {
      caseDiameter: '39 mm',
      caseThickness: '8 mm',
      caseMaterial: 'Grade 5 Aerospace Titanium',
      waterResistance: '50 Meters / 5 ATM',
      movement: 'Solar Powered',
      glass: 'Flat Anti-Reflective Sapphire',
      strapWidth: '20 mm',
      dialColor: 'Matte Slate Gray',
      warranty: '3 Year Eco-Solar Warranty',
      powerReserve: '6 Months Dark Reserve'
    }
  }
];

export const DEMO_REVIEWS: ProductReview[] = [
  {
    id: 'rev-1',
    productId: 'prod-04',
    author: 'Alexander Wright',
    age: 32,
    rating: 5,
    date: '2026-08-14',
    title: 'An absolute masterpiece on the wrist!',
    content: 'The skeleton movement is mesmerizing. I catch myself just staring at the balance wheel during meetings. The rose gold plating has a very refined, deep warmth rather than looking flashy. Delivery was fast and came in a premium velvet-lined box.',
    verifiedPurchase: true,
    userLocation: 'London, UK',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'rev-2',
    productId: 'prod-04',
    author: 'Marcus Vance',
    age: 36,
    rating: 5,
    date: '2026-08-28',
    title: 'Superior quality that rivals $5,000 Swiss brands',
    content: 'I own several Swiss timepieces, and the finishing on this Grand Sovereign Skeleton blew me away. The leather strap is real top-grain alligator and feels broke-in from day one. Unbelievable value.',
    verifiedPurchase: true,
    userLocation: 'New York, USA',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'rev-3',
    productId: 'prod-01',
    author: 'Liam Chen',
    age: 19,
    rating: 5,
    date: '2026-09-02',
    title: 'Super sleek and fits my streetwear vibe perfectly!',
    content: 'I get so many compliments at university. The orange and black contrast looks futuristic, and the backlight function is clear at night. Heavy duty strap too.',
    verifiedPurchase: true,
    userLocation: 'Vancouver, Canada',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'rev-4',
    productId: 'prod-08',
    author: 'Sir David Sterling',
    age: 54,
    rating: 5,
    date: '2026-07-20',
    title: 'The Tourbillon mechanism is horological perfection.',
    content: 'Purchased as a milestone gift for my 55th birthday. The flying tourbillon movement rotates smoothly without a hiccup. The presentation wooden box winder alone is a work of art. Truly a proud collector piece.',
    verifiedPurchase: true,
    userLocation: 'Geneva, Switzerland',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'rev-5',
    productId: 'prod-02',
    author: 'Sophia Martinez',
    age: 22,
    rating: 5,
    date: '2026-08-10',
    title: 'Minimalist dream watch',
    content: 'Bought this for my partner for graduation and he wears it everywhere. Super comfortable mesh strap and blue steel hands look subtle yet expensive.',
    verifiedPurchase: true,
    userLocation: 'Madrid, Spain',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80'
  },
  {
    id: 'rev-6',
    productId: 'prod-09',
    author: 'Arthur Pendelton',
    age: 48,
    rating: 5,
    date: '2026-08-01',
    title: 'Stunning moonphase indicator and Roman indices',
    content: 'The enamel moonphase wheel is gorgeous under sunlight. Keeps excellent time and has a substantial, noble presence on the wrist.',
    verifiedPurchase: true,
    userLocation: 'Melbourne, Australia',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=150&q=80'
  }
];

export const CATEGORIES = [
  { id: 'all', label: 'All Watches', icon: 'Watch' },
  { id: 'Dress', label: 'Dress & Heritage', icon: 'Crown' },
  { id: 'Sport', label: 'Sport & Speed', icon: 'Zap' },
  { id: 'Dive', label: 'Deep Water Diver', icon: 'Compass' },
  { id: 'Luxury', label: 'Haute Luxury', icon: 'Gem' },
  { id: 'Minimalist', label: 'Modern Minimalist', icon: 'Feather' },
  { id: 'Skeleton', label: 'Skeleton & Open-Heart', icon: 'Cpu' },
  { id: 'Digital', label: 'Cyber & Digital', icon: 'Activity' },
  { id: 'Chronograph', label: 'Chronograph', icon: 'Clock' },
];

export const AGE_GROUPS = [
  {
    id: '15-24',
    title: 'Youth & Next Gen (15–24)',
    subtitle: 'Urban streetwear, cyber hybrids, sleek minimalists & bold statement pieces',
    bgImage: 'https://images.unsplash.com/photo-1511370235399-1802cae1d32f?auto=format&fit=crop&w=800&q=80',
    badge: 'Trending with Gen Z'
  },
  {
    id: '25-38',
    title: 'Modern Professional (25–38)',
    subtitle: 'Skeleton automatic mechanicals, steel sport divers & executive chronographs',
    bgImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=80',
    badge: 'Career & Lifestyle'
  },
  {
    id: '39-60',
    title: 'Executive & Heritage (39–60+)',
    subtitle: 'Flying Tourbillons, Perpetual Moonphase calendars & 18K Gold classics',
    bgImage: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
    badge: 'Master Connoisseurs'
  }
];

export const BRANDS = [
  'Aura Horology',
  'Sovereign Geneva',
  'Chronos Lab',
  'Vance & Co.',
  'Veloce Geneva'
];

export const PROMO_CODES: Record<string, number> = {
  'WELCOME10': 10,
  'TIMELESS15': 15,
  'LUXURY20': 20,
  'GENZ25': 25,
};
